# Generated by Django 4.2.16 on 2026-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, help_text='City, State', max_length=255, null=True)),
                ('college_type', models.CharField(choices=[('iit', 'IIT'), ('nit', 'NIT'), ('iiit', 'IIIT'), ('central', 'Central University'), ('state', 'State University'), ('deemed', 'Deemed University'), ('private', 'Private'), ('other', 'Other')], default='other', max_length=20)),
                ('affiliation', models.CharField(blank=True, help_text='Affiliated board / university', max_length=255, null=True)),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='NIRF or equivalent national rank', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(help_text='Organisation or government body offering the scholarship', max_length=255)),
                ('description', models.TextField()),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit Based'), ('need', 'Need Based'), ('sports', 'Sports'), ('minority', 'Minority'), ('government', 'Government'), ('private', 'Private'), ('other', 'Other')], default='merit', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Annual scholarship amount in INR', max_digits=12, null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Application deadline', null=True)),
                ('application_url', models.URLField(blank=True, help_text='Link to apply', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
